### ISSUE TITLE
LTS release 5.0.5 missing

### ISSUE THREAD

**Issue by maxnoe** [conda-forge/astropy-feedstock#118]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There seems to be no conda-forge release for the 5.0.5 LTS bugfix release

**Comment by maxnoe** [comment]
I was about to open a PR, but I realize that's not possible, since you cannot add a new branch to a repo via pull request.

I checked the differences, and I think we can just take the current recipe and change version and hash to the 5.0.5 release.

You can take it from here: https://github.com/maxnoe/astropy-feedstock/tree/v5.0.x

**Comment by pllim** [comment]
Thank you!
