### ISSUE TITLE
Uncaptured requirement of Numpy < 2 on Windows

### ISSUE THREAD

**Issue by pkgw** [conda-forge/astropy-feedstock#140]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This issue inspired by something I've run into in https://github.com/conda-forge/toasty-feedstock/pull/36 . It appears that the latest `astropy` package, `6.1.1-*_0` contains pip metadata indicating that it is not compatible with Numpy 2.0 on Windows. Specifically, in my test environment, `lib/python3.12/site-packages/astropy-6.1.1.dist-info/METADATA` contains:

```
Requires-Dist: numpy >=1.23
[...]
Requires-Dist: numpy <2.0 ; platform_system == "Windows"
```

But this constraint is not reflected in the Conda metadata. So, Conda will let you install this package into a Numpy 2.0 environment on Windows, but then anything at the `pip` level starts giving errors.

If I download the conda-forge package for 6.1.0, the second `numpy` line with the Windows constraint is not present.

At a minimum,. the 6.1.1 Windows packages should have their repodata patched to capture this constraint. But I'm filing the issue here because

1. Maybe this feedstock needs to be changed to capture this constraint for future builds? However, I cannot figure out where the constraint is actually coming from; as best I can tell it's not explicit in the Astropy source anywhere.
2. I don't have a sense as to whether previous versions should also have their repodata patched. I would guess that all older versions might also be incompatible with Numpy 2 on Windows, not just 6.1.1, but I'm unfamiliar with any related discussions.

### Installed packages

```shell
On my Linux environment where the METADATA file has the relevant constraint:

astropy                   6.1.1           py312h085067d_0    conda-forge
numpy                     2.0.0           py312h22e1c76_0    conda-forge
```

### Environment info

```shell
N/A
```

**Comment by pkgw** [comment]
Ah, of course, right after I file the bug, I find some more information:

https://github.com/astropy/astropy/issues/16578
https://github.com/astropy/astropy/pull/16579
https://github.com/astropy/astropy/pull/16581

So my initial read is that only the 6.1.1 / Windows packages need to have their repodata patched.

**Comment by pkgw** [comment]
Filed https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/803 to address the Windows 6.1.1 packages. If anything else needs modification, we can extend those changes.

**Comment by neutrinoceros** [comment]
> Maybe this feedstock needs to be changed to capture this constraint for future builds? However, I cannot figure out where the constraint is actually coming from; as best I can tell it's not explicit in the Astropy source anywhere.

That's because we fixed it very shortly after we released 6.1.1 ! next version will not have this constraint

**Comment by pllim** [comment]
This PR can be closed now. Thanks!

**Comment by pkgw** [comment]
Yes, I'll close this. Felipe did make a correct comment in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/803 though: if another build of the 6.1.1 release is made in this feedstock as-is, the Windows metadata will be wrong again. My impression is that it is likely that we'll see a 6.1.2 soon, though, so I tend to think that it is better to *not* modify the feedstock right now, but it could probably go either way.

**Comment by pllim** [comment]
@mwcraig , what do you think? Should we have at least a draft PR out in this repo to remind ourselves when 6.1.2 is out?

**Comment by mwcraig** [comment]
If I understand correctly we won't need to for 6.1.2. 

I can open a PR to a new build for 6.1.1 that includes this restriction on windows and also drops the patch that we aren't using any more (#139)
