### ISSUE TITLE
Simultaneously package LTS and latest versions

### ISSUE THREAD

**Issue by pkgw** [conda-forge/astropy-feedstock#25]
I've been told that it'd be desirable to package two versions of Astropy: the LTS series, and the latest releases of the (currently) 3.x branch (cf. discussion in #23)

To the best of my understanding, this can be achieved simply by creating a new branch in this feestock repository. I'd recommend creating one called `lts` that includes the feedstock from just before the merger of #24. Updates to the LTS could then be accomplished by PRs to that branch, and updates to the mainline could be accomplished by PRs to master.

**Comment by bsipocz** [comment]
Thanks @pkgw! Would you think we should do it now, it's OK to wait until the next bugfix releases?

**Comment by pkgw** [comment]
I guess I'd be inclined to say set it up now while the topic is fresh in mind, but I'm pretty sure it's fine either way.

**Comment by bsipocz** [comment]
This is done now with the latest releases.
