### ISSUE TITLE
Fresh Python 3.6 install mixes defaults and conda-forge packages when installing astropy

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/astropy-feedstock#31]
One of the dependencies of the astropy conda-forge package seems to point to something that is only available in the `defaults` channel, apparently something related to intel-openmp/mkl, leading to even pulling in the `defaults` numpy instead of using `conda-forge`s numpy.
This leads to all kinds of messes when trying to install other packages from conda-forge that point to its numpy package.
Can you investigate what is happening? The steps to reproduce are really simple:

* conda 4.5.3, on macOS 10.12.6, two channels defined, `defaults` and `conda-forge`, with `conda-forge` being superior.
* `conda create -n TEST python=3 -y`
* `conda activate TEST`

giving you this:
```
(test2) └─❱❱❱ conda list                                                            +8041 12:36 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/test2:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2o                        0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
python                    3.6.5                         1    conda-forge
readline                  7.0                           0    conda-forge
setuptools                39.1.0                   py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
* `conda install astropy`

and then you get this:
```
(test2) └─❱❱❱ conda install astropy                                                 +8036 12:28 ❰─┘
Solving environment: done

## Package Plan ##

  environment location: /Users/klay6683/miniconda3/envs/test2

  added / updated specs:
    - astropy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.14.2               |   py36ha9ae307_1         4.0 MB

The following NEW packages will be INSTALLED:

    astropy:            3.0.2-py36_1          conda-forge
    attrs:              18.1.0-py_0           conda-forge
    intel-openmp:       2018.0.0-8
    libgfortran:        3.0.1-h93005f0_2
    mkl:                2018.0.2-1
    mkl_fft:            1.0.2-py36_0          conda-forge
    mkl_random:         1.0.1-py36_0          conda-forge
    more-itertools:     4.1.0-py_0            conda-forge
    numpy:              1.14.2-py36ha9ae307_1
    pluggy:             0.6.0-py_0            conda-forge
    psutil:             5.4.5-py36_0          conda-forge
    py:                 1.5.3-py_0            conda-forge
    pytest:             3.5.1-py36_0          conda-forge
    pytest-arraydiff:   0.2-py_0              conda-forge
    pytest-astropy:     0.2.1-py_0            conda-forge
    pytest-doctestplus: 0.1.2-py_0            conda-forge
    pytest-openfiles:   0.2.0-py_0            conda-forge
    pytest-remotedata:  0.2.0-py_0            conda-forge
    six:                1.11.0-py36_1         conda-forge

Proceed ([y]/n)? n
```

**Comment by michaelaye** [comment]
If one of the many dependencies of astropy lists a funny dependency, it's not a resolver issue but a package maintainer issue, isn't it?

**Comment by bsipocz** [comment]
As I said, we can't do anything about it here, it's clearly a conda issue (if it's an issue at all...). 

btw, astropy doesn't have many dependencies, the only one there is numpy, you can easily check it in the the recipe in this repo.

**Comment by michaelaye** [comment]
Not what I see here on macOS.

`astropy` depends on:

```
dependencies:
    numpy >=1.11
    pytest-astropy
    python 3.6*
```

`pytest-astropy` depends on:
```
dependencies:
    pytest >=3.1
    pytest-arraydiff >=0.1
    pytest-doctestplus >=0.1.2
    pytest-openfiles >=0.2
    pytest-remotedata >=0.2
    python
```
with all those pytest-xxx packages being extra packages for `astropy` only.
There's a lot here that could go wrong potentially, if only one of those packages has a funny dependency somewhere.
It would be interesting to see the results from someone else executing the provided steps to reproduce to confirm or disprove if this happens everywhere? I am getting these results on 2 different Macs and one Linux distro with a much older `conda` 4.4.10 (the dependencies in Linux also include pytest-astropy).

**Comment by michaelaye** [comment]
The issue seems to be related to `pytest-arraydiff` as I researched for this issue: https://github.com/conda/conda/issues/7299
