### ISSUE TITLE
Python 2 compiled extensions are linking to VCRUNTIME140.dll instead of MSVCR90.dll

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/astropy-feedstock#38]
Since v2.0.4, the conda packages are suffering from this issue:

```
(base) C:\Users\Wani\Miniconda2\Lib\site-packages\astropy\utils>ntldd _compiler.pyd
        python27.dll => C:\Users\Wani\Miniconda2\python27.dll (0x0000000000b10000)
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000000000720000)
        VCRUNTIME140.dll => not found
```

I think the problematic commit is: https://github.com/conda-forge/astropy-feedstock/pull/22/commits/a0e921101192c66c80b47c84ec9253417175d5a7 which brings in:
https://github.com/conda-forge/astropy-feedstock/blob/a0e921101192c66c80b47c84ec9253417175d5a7/recipe/bld.bat#L1-L3

cc @bsipocz

**Comment by nehaljwani** [comment]
The build works fine on my machine if I revert that patch.

**Comment by mwcraig** [comment]
Closing since we aren't supporting Python2 any more.
