### ISSUE TITLE
Astropy with numpy 1.12

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/astropy-feedstock#6]
To be able to build certain affiliated packages with numpy 1.12 (e.g. reproject), I need astropy builds for np 1.12, too.

@astrofrog @mwcraig - Should we do that here, or wait for them to appear in the default channel?

**Comment by mwcraig** [comment]
Not sure whether we just edit the feedstock or rerender the feedstock or something else. Have asked here: https://groups.google.com/forum/#!topic/conda-forge/OgWwiq23ZJ8

**Comment by mwcraig** [comment]
Looks like the blocker right now is numpy 1.12 for windows. See this issue which is tracking builds for the numpy 1.12 release: https://github.com/conda-forge/conda-forge.github.io/issues/313

**Comment by bsipocz** [comment]
That's a pity, as we don't care that much about the windows builds as quite a few packages downstream don't even support that. (And while np1.12 is not available on windows the builds there are not picking it up and failing with missing dependencies such as astropy).
