### ISSUE TITLE
Remove Travis?

### ISSUE THREAD

**Issue by adrn** [conda-forge/astropy-feedstock#90]
Quick note: It looks like this feedstock is still using Travis for some builds -- those should probably be removed / moved to another CI service!

**Comment by adrn** [comment]
Oops - Travis builds failed for v4.2.1 and I misunderstood why https://travis-ci.com/github/conda-forge/astropy-feedstock/jobs/495578143

**Comment by bsipocz** [comment]
A restart has solved that failure.

 I'm closing this issue now.
